-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-05 11:15:25 BRT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE aula 
    ( 
     id_aula          NUMBER (5)  NOT NULL , 
     nome             VARCHAR2 (50)  NOT NULL , 
     descricao        VARCHAR2 (100)  NOT NULL , 
     pontos_aula      NUMBER (5)  NOT NULL , 
     dificuldade      VARCHAR2 (20)  NOT NULL , 
     conteudo         VARCHAR2 (1000)  NOT NULL , 
     concluida        NUMBER  NOT NULL , 
     modulo_id_modulo NUMBER (5)  NOT NULL 
    ) 
;

ALTER TABLE aula 
    ADD CONSTRAINT aula_PK PRIMARY KEY ( id_aula ) ;

CREATE TABLE bairro 
    ( 
     id_bairro        NUMBER (3)  NOT NULL , 
     nome_bairro      VARCHAR2 (30)  NOT NULL , 
     cidade_id_cidade NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE bairro 
    ADD CONSTRAINT bairro_PK PRIMARY KEY ( id_bairro ) ;

CREATE TABLE cidade 
    ( 
     id_cidade        NUMBER (3)  NOT NULL , 
     nome_cidade      VARCHAR2 (30)  NOT NULL , 
     estado_id_estado NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE cidade 
    ADD CONSTRAINT cidade_PK PRIMARY KEY ( id_cidade ) ;

CREATE TABLE endereco 
    ( 
     id_endereco      NUMBER (3)  NOT NULL , 
     cep              VARCHAR2 (8)  NOT NULL , 
     rua              VARCHAR2 (150)  NOT NULL , 
     numero           VARCHAR2 (5)  NOT NULL , 
     bairro_id_bairro NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE endereco 
    ADD CONSTRAINT endereco_PK PRIMARY KEY ( id_endereco ) ;

CREATE TABLE estado 
    ( 
     id_estado   NUMBER (3)  NOT NULL , 
     nome_estado VARCHAR2 (30)  NOT NULL 
    ) 
;

ALTER TABLE estado 
    ADD CONSTRAINT estado_PK PRIMARY KEY ( id_estado ) ;

CREATE TABLE historico 
    ( 
     id_hist    NUMBER (3)  NOT NULL , 
     tipo_hist  VARCHAR2 (30)  NOT NULL , 
     data_hist  TIMESTAMP  NOT NULL , 
     pet_id_pet NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE historico 
    ADD CONSTRAINT historico_PK PRIMARY KEY ( id_hist ) ;

CREATE TABLE modulo 
    ( 
     id_modulo        NUMBER (5)  NOT NULL , 
     nome             VARCHAR2 (50)  NOT NULL , 
     tempo_conclusao  VARCHAR2 (10)  NOT NULL , 
     descricao        VARCHAR2 (100)  NOT NULL , 
     trilha_id_trilha NUMBER (5)  NOT NULL 
    ) 
;

ALTER TABLE modulo 
    ADD CONSTRAINT modulo_PK PRIMARY KEY ( id_modulo ) ;

CREATE TABLE pet 
    ( 
     id_pet       NUMBER (3)  NOT NULL , 
     nome         VARCHAR2 (30)  NOT NULL , 
     data_nasc    DATE  NOT NULL , 
     sexo         VARCHAR2 (1)  NOT NULL , 
     porte        VARCHAR2 (10)  NOT NULL , 
     castrado     NUMBER  NOT NULL , 
     raca_id_raca NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE pet 
    ADD 
    CHECK (sexo IN ('F', 'M')) 
;

ALTER TABLE pet 
    ADD 
    CHECK (porte IN ('GRANDE', 'MEDIO', 'PEQUENO')) 
;

ALTER TABLE pet 
    ADD CONSTRAINT pet_PK PRIMARY KEY ( id_pet ) ;

CREATE TABLE raca 
    ( 
     id_raca   NUMBER (3)  NOT NULL , 
     nome_raca VARCHAR2 (30)  NOT NULL 
    ) 
;

ALTER TABLE raca 
    ADD CONSTRAINT raca_PK PRIMARY KEY ( id_raca ) ;

CREATE TABLE status 
    ( 
     id_status   NUMBER (3)  NOT NULL , 
     nome_status VARCHAR2 (15)  NOT NULL 
    ) 
;

ALTER TABLE status 
    ADD 
    CHECK (nome_status IN ('CONCLUIDO', 'EXPIRADO', 'PENDENTE')) 
;

ALTER TABLE status 
    ADD CONSTRAINT status_PK PRIMARY KEY ( id_status ) ;

CREATE TABLE tarefa 
    ( 
     id_tarefa          NUMBER (3)  NOT NULL , 
     titulo             VARCHAR2 (30)  NOT NULL , 
     pontos_tarefa      NUMBER (3)  NOT NULL , 
     descricao          VARCHAR2 (200)  NOT NULL , 
     criacao            TIMESTAMP  NOT NULL , 
     prazo              TIMESTAMP  NOT NULL , 
     conclusao          TIMESTAMP , 
     pet_id_pet         NUMBER (3)  NOT NULL , 
     status_id_status   NUMBER (3)  NOT NULL , 
     usuario_id_usuario NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE tarefa 
    ADD CONSTRAINT tarefa_PK PRIMARY KEY ( id_tarefa ) ;

CREATE TABLE telefone 
    ( 
     id_telefone NUMBER (3)  NOT NULL , 
     num_ddd     VARCHAR2 (2)  NOT NULL , 
     num_tel     VARCHAR2 (9)  NOT NULL 
    ) 
;

ALTER TABLE telefone 
    ADD CONSTRAINT telefone_PK PRIMARY KEY ( id_telefone ) ;

CREATE TABLE trilha 
    ( 
     id_trilha  NUMBER (5)  NOT NULL , 
     nome       VARCHAR2 (30)  NOT NULL , 
     descricao  VARCHAR2 (200)  NOT NULL , 
     pet_id_pet NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE trilha 
    ADD CONSTRAINT trilha_PK PRIMARY KEY ( id_trilha ) ;

CREATE TABLE usuario 
    ( 
     id_usuario           NUMBER (3)  NOT NULL , 
     nome                 VARCHAR2 (100)  NOT NULL , 
     email                VARCHAR2 (50)  NOT NULL , 
     senha                VARCHAR2 (60)  NOT NULL , 
     role                 VARCHAR2 (10)  NOT NULL , 
     telefone_id_telefone NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE usuario 
    ADD 
    CHECK (role IN ('ADMIN', 'COMUM', 'PREMIUM')) 
;
CREATE UNIQUE INDEX usuario__IDX ON usuario 
    ( 
     telefone_id_telefone ASC 
    ) 
;

ALTER TABLE usuario 
    ADD CONSTRAINT usuario_PK PRIMARY KEY ( id_usuario ) ;

ALTER TABLE usuario 
    ADD CONSTRAINT usuario_email_UN UNIQUE ( email ) ;

CREATE TABLE usuario_endereco 
    ( 
     usuario_id_usuario   NUMBER (3)  NOT NULL , 
     endereco_id_endereco NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE usuario_endereco 
    ADD CONSTRAINT usuario_endereco_PK PRIMARY KEY ( usuario_id_usuario, endereco_id_endereco ) ;

CREATE TABLE usuario_pet 
    ( 
     usuario_id_usuario NUMBER (3)  NOT NULL , 
     pet_id_pet         NUMBER (3)  NOT NULL , 
     respon_princ       NUMBER  NOT NULL 
    ) 
;

ALTER TABLE usuario_pet 
    ADD CONSTRAINT usuario_pet_PK PRIMARY KEY ( usuario_id_usuario, pet_id_pet ) ;

ALTER TABLE aula 
    ADD CONSTRAINT aula_modulo_FK FOREIGN KEY 
    ( 
     modulo_id_modulo
    ) 
    REFERENCES modulo 
    ( 
     id_modulo
    ) 
;

ALTER TABLE bairro 
    ADD CONSTRAINT bairro_cidade_FK FOREIGN KEY 
    ( 
     cidade_id_cidade
    ) 
    REFERENCES cidade 
    ( 
     id_cidade
    ) 
;

ALTER TABLE cidade 
    ADD CONSTRAINT cidade_estado_FK FOREIGN KEY 
    ( 
     estado_id_estado
    ) 
    REFERENCES estado 
    ( 
     id_estado
    ) 
;

ALTER TABLE endereco 
    ADD CONSTRAINT endereco_bairro_FK FOREIGN KEY 
    ( 
     bairro_id_bairro
    ) 
    REFERENCES bairro 
    ( 
     id_bairro
    ) 
;

ALTER TABLE historico 
    ADD CONSTRAINT historico_pet_FK FOREIGN KEY 
    ( 
     pet_id_pet
    ) 
    REFERENCES pet 
    ( 
     id_pet
    ) 
;

ALTER TABLE modulo 
    ADD CONSTRAINT modulo_trilha_FK FOREIGN KEY 
    ( 
     trilha_id_trilha
    ) 
    REFERENCES trilha 
    ( 
     id_trilha
    ) 
;

ALTER TABLE pet 
    ADD CONSTRAINT pet_raca_FK FOREIGN KEY 
    ( 
     raca_id_raca
    ) 
    REFERENCES raca 
    ( 
     id_raca
    ) 
;

ALTER TABLE tarefa 
    ADD CONSTRAINT tarefa_pet_FK FOREIGN KEY 
    ( 
     pet_id_pet
    ) 
    REFERENCES pet 
    ( 
     id_pet
    ) 
;

ALTER TABLE tarefa 
    ADD CONSTRAINT tarefa_status_FK FOREIGN KEY 
    ( 
     status_id_status
    ) 
    REFERENCES status 
    ( 
     id_status
    ) 
;

ALTER TABLE tarefa 
    ADD CONSTRAINT tarefa_usuario_FK FOREIGN KEY 
    ( 
     usuario_id_usuario
    ) 
    REFERENCES usuario 
    ( 
     id_usuario
    ) 
;

ALTER TABLE trilha 
    ADD CONSTRAINT trilha_pet_FK FOREIGN KEY 
    ( 
     pet_id_pet
    ) 
    REFERENCES pet 
    ( 
     id_pet
    ) 
;

ALTER TABLE usuario_endereco 
    ADD CONSTRAINT usuario_endereco_endereco_FK FOREIGN KEY 
    ( 
     endereco_id_endereco
    ) 
    REFERENCES endereco 
    ( 
     id_endereco
    ) 
;

ALTER TABLE usuario_endereco 
    ADD CONSTRAINT usuario_endereco_usuario_FK FOREIGN KEY 
    ( 
     usuario_id_usuario
    ) 
    REFERENCES usuario 
    ( 
     id_usuario
    ) 
;

ALTER TABLE usuario_pet 
    ADD CONSTRAINT usuario_pet_pet_FK FOREIGN KEY 
    ( 
     pet_id_pet
    ) 
    REFERENCES pet 
    ( 
     id_pet
    ) 
;

ALTER TABLE usuario_pet 
    ADD CONSTRAINT usuario_pet_usuario_FK FOREIGN KEY 
    ( 
     usuario_id_usuario
    ) 
    REFERENCES usuario 
    ( 
     id_usuario
    ) 
;

ALTER TABLE usuario 
    ADD CONSTRAINT usuario_telefone_FK FOREIGN KEY 
    ( 
     telefone_id_telefone
    ) 
    REFERENCES telefone 
    ( 
     id_telefone
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                             37
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
